# Generated by Django 4.2.7 on 2023-12-02 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WixUser',
            fields=[
                ('instance_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('site_id', models.CharField(max_length=200, unique=True)),
                ('user_id', models.CharField(max_length=200, unique=True)),
                ('refresh_token', models.CharField(max_length=200, unique=True)),
                ('is_free', models.BooleanField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComponentSlider',
            fields=[
                ('component_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('before_image', models.CharField(max_length=1000)),
                ('before_label_text', models.CharField(max_length=1000)),
                ('before_alt_text', models.CharField(max_length=1000)),
                ('after_image', models.CharField(max_length=1000)),
                ('after_label_text', models.CharField(max_length=1000)),
                ('after_alt_text', models.CharField(max_length=1000)),
                ('offset', models.IntegerField()),
                ('offset_float', models.FloatField()),
                ('is_vertical', models.BooleanField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('instance_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sliders.wixuser')),
            ],
        ),
    ]
