# Generated by Django 4.2.7 on 2023-12-03 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sliders', '0002_appextension_rename_wixuser_appuser_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppExtension',
            new_name='Extension',
        ),
        migrations.RenameModel(
            old_name='AppUser',
            new_name='User',
        ),
    ]
