# Generated by Django 4.2.7 on 2023-12-05 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sliders', '0003_rename_appextension_extension_rename_appuser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extension',
            name='after_alt_text',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='extension',
            name='after_image',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='extension',
            name='after_label_text',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='extension',
            name='before_alt_text',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='extension',
            name='before_image',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='extension',
            name='before_label_text',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='extension',
            name='extension_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='instance_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='refresh_token',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='site_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
