# Generated by Django 4.2.7 on 2023-12-07 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sliders', '0004_alter_extension_after_alt_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extension',
            name='is_overlay_disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='extension',
            name='is_vertical',
            field=models.BooleanField(default=False),
        ),
    ]
