# Generated by Django 4.2.7 on 2023-12-08 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sliders', '0005_extension_is_overlay_disabled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extension',
            name='is_overlay_disabled',
        ),
        migrations.AddField(
            model_name='extension',
            name='is_overlay_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
