# Generated by Django 4.2.7 on 2023-12-09 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sliders', '0006_remove_extension_is_overlay_disabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extension',
            name='is_move_on_hover_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
