# Generated by Django 4.2.7 on 2023-12-09 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sliders', '0009_extension_mouseover_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extension',
            name='is_move_on_hover_enabled',
        ),
        migrations.RemoveField(
            model_name='extension',
            name='is_overlay_enabled',
        ),
    ]
