# Generated by Django 4.2.7 on 2023-12-13 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sliders', '0012_alter_user_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
    ]
