# Generated by Django 4.2.7 on 2023-12-13 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sliders', '0013_remove_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extension',
            name='after_alt_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='extension',
            name='after_label_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='extension',
            name='before_alt_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='extension',
            name='before_label_text',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
